name: Deploy update_company_status

on:
  push:
    branches: [dev]
    paths:
      - "src/lambdas/update_company_status/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws_account_id: ${{ vars.AWS_DEV_ACCOUNT_ID }}
      aws_iam_role_for_lambda_deployer_arn: ${{ vars.AWS_IAM_ROLE_FOR_LAMBDA_DEPLOYER }}
      aws_region: ${{ vars.AWS_GLOBAL_REGION }}
      lambda_directory: src/lambdas/update_company_status
      lambda_name: update_company_status
      python_version: "3.14"
