name: Deploy extract_company_persons

on:
  push:
    branches: [main]
    paths:
      - "src/lambdas/extract_company_persons/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws_iam_role_for_lambda_deployer_arn: ${{ vars.AWS_IAM_ROLE_FOR_LAMBDA_DEPLOYER }}
      aws_region: ${{ vars.AWS_GLOBAL_REGION }}
      lambda_directory: src/lambdas/extract_company_persons
      lambda_name: extract_company_persons
      python_version: "3.14"
